spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: transfer
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password